[package]
authors = ["Jorge Aparicio <jorge@japaric.io>"]
name = "ble400"
version = "0.1.0"

[build-dependencies]
gcc = "0.3.46"

[dependencies]
aligned = "0.1.1"
cortex-m-semihosting = "0.1.3"
cty = "0.1.5"

[profile]

[profile.release]
debug = true
